// Sample data for Matchboard UI kit. Names, disciplines, project titles are fictional.
// Kept editorial-feeling: real-sounding research areas, plausible h-indexes, varied disciplines.

const DISCIPLINES = [
  "Materials Science", "Bioengineering", "Computational Biology",
  "Climate Science", "Linguistics", "Medieval Studies",
  "Computer Science", "Public Health", "Economics",
  "Chemistry", "Physics", "Ethics", "Neuroscience",
  "Anthropology", "Environmental Engineering",
];

const RESEARCHERS = [
  {
    id: "r-okonkwo",
    initials: "AO",
    name: "Dr. Adaeze Okonkwo",
    title: "Associate Professor",
    discipline: "Materials Science",
    department: "Dept. of Materials & Chemical Engineering",
    bio: "Self-healing polymers, biocompatible coatings, and the molecular design of degradable scaffolds for implantable devices. Currently building a lab translating polymer chemistry into clinical-stage prototypes.",
    skills: ["polymers", "biomedical materials", "tissue engineering", "polymer chemistry", "FTIR", "rheology", "scaffolds"],
    publications: 42,
    hIndex: 31,
    openCollaborations: 3,
    avatarHue: 0,
    matchPct: 87,
    matchReasons: ["polymers", "biomedical", "tissue engineering"],
  },
  {
    id: "r-kowalski",
    initials: "JK",
    name: "Jakub Kowalski",
    title: "Postdoctoral Fellow",
    discipline: "Computational Biology",
    department: "Centre for Genomic Medicine",
    bio: "Single-cell transcriptomics, batch-effect correction, and the open tooling that lets wet-lab biologists run their own analyses without writing R.",
    skills: ["single-cell", "bioinformatics", "RNA-seq", "Python", "Nextflow", "statistics"],
    publications: 18,
    hIndex: 14,
    openCollaborations: 2,
    avatarHue: 1,
    matchPct: 71,
    matchReasons: ["single-cell", "bioinformatics"],
  },
  {
    id: "r-marin",
    initials: "SM",
    name: "Dr. Sofía Marín",
    title: "Senior Lecturer",
    discipline: "Ethics",
    department: "Faculty of Philosophy",
    bio: "Research ethics in emerging biotechnologies, with an emphasis on informed consent in vulnerable populations and regulatory science for novel biomaterials.",
    skills: ["ethics review", "regulatory", "informed consent", "qualitative methods", "policy"],
    publications: 27,
    hIndex: 19,
    openCollaborations: 1,
    avatarHue: 2,
    matchPct: 54,
    matchReasons: ["ethics review", "regulatory"],
  },
  {
    id: "r-patel",
    initials: "RP",
    name: "Dr. Rohan Patel",
    title: "Research Fellow",
    discipline: "Computer Science",
    department: "School of Informatics",
    bio: "Probabilistic programming, surrogate models for expensive simulations, and a long-running collaboration with the climate group on emulator design.",
    skills: ["computational modeling", "machine learning", "Bayesian methods", "PyTorch", "simulation"],
    publications: 22,
    hIndex: 16,
    openCollaborations: 4,
    avatarHue: 3,
    matchPct: 32,
    matchReasons: ["computational modeling"],
  },
  {
    id: "r-lindqvist",
    initials: "EL",
    name: "Dr. Emil Lindqvist",
    title: "Research Engineer",
    discipline: "Bioengineering",
    department: "Centre for Translational Medicine",
    bio: "Bench-to-bedside translation of implantable devices. Strong on biocompatibility testing, regulatory pre-submissions, and pilot-scale manufacturing.",
    skills: ["biocompatibility", "implants", "ISO 10993", "GMP", "translational"],
    publications: 31,
    hIndex: 22,
    openCollaborations: 2,
    avatarHue: 0,
    matchPct: 79,
    matchReasons: ["biocompatibility", "implants", "translational"],
  },
  {
    id: "r-nakamura",
    initials: "HN",
    name: "Dr. Haruki Nakamura",
    title: "Professor",
    discipline: "Climate Science",
    department: "Dept. of Earth Sciences",
    bio: "Atmosphere-ocean coupling at decadal timescales. Builds the institute's flagship Earth-system model and chairs the inter-faculty data infrastructure committee.",
    skills: ["climate modeling", "atmospheric physics", "data infrastructure", "Fortran", "HPC"],
    publications: 88,
    hIndex: 44,
    openCollaborations: 5,
    avatarHue: 1,
    matchPct: 41,
    matchReasons: ["climate modeling"],
  },
];

const PROJECTS = [
  {
    id: "p-141",
    code: "DRS-2026-0141",
    title: "Self-healing polymers for biomedical implants",
    discipline: "Materials Science",
    status: "Open",
    posted: "4 days ago",
    deadline: "2 weeks",
    duration: "12 months",
    funded: true,
    lead: { name: "Dr. Adaeze Okonkwo", id: "r-okonkwo", initials: "AO" },
    description: "Seeking two collaborators with backgrounds in tissue engineering or biocompatibility testing. The project develops self-healing polymer coatings for cardiovascular implants, with partial funding secured through the Translational Medicine Seed Fund.",
    longDescription: "We are designing a class of supramolecular polymers that re-form covalent crosslinks at body temperature after mechanical damage. The first 6 months focus on synthesis and rheological characterisation; the back half pivots to in-vitro biocompatibility and a pre-clinical animal model. Collaborators with regulatory and ethics-review experience are also welcome — we expect to file a pre-IDE submission late in year one.",
    requiredSkills: ["tissue engineering", "biocompatibility", "biomedical materials"],
    niceSkills: ["regulatory", "ethics review", "ISO 10993"],
    candidateIds: ["r-okonkwo", "r-lindqvist", "r-marin", "r-patel"],
    matchPct: 87,
  },
  {
    id: "p-138",
    code: "DRS-2026-0138",
    title: "Single-cell atlas of pancreatic ductal adenocarcinoma",
    discipline: "Computational Biology",
    status: "Open",
    posted: "1 week ago",
    deadline: "5 days",
    duration: "18 months",
    funded: true,
    lead: { name: "Jakub Kowalski", id: "r-kowalski", initials: "JK" },
    description: "Building a reference atlas across 200+ patient samples. Need a wet-lab partner with PDAC tissue access and a clinical-genomics collaborator with experience in mutational signature analysis.",
    longDescription: "The atlas will combine 10x scRNA-seq and spatial transcriptomics across a large patient cohort. We are looking for a pathology lead, a clinical genomicist familiar with mutational-signature pipelines, and ideally a clinical-trials partner to surface candidate stratification markers.",
    requiredSkills: ["single-cell", "bioinformatics", "RNA-seq"],
    niceSkills: ["pathology", "clinical genomics"],
    candidateIds: ["r-kowalski", "r-marin"],
    matchPct: 71,
  },
  {
    id: "p-130",
    code: "DRS-2026-0130",
    title: "Emulators for Earth-system model perturbed ensembles",
    discipline: "Climate Science",
    status: "Open",
    posted: "2 weeks ago",
    deadline: "Closing today",
    deadlineUrgent: true,
    duration: "9 months",
    funded: false,
    lead: { name: "Dr. Haruki Nakamura", id: "r-nakamura", initials: "HN" },
    description: "Replacing the most expensive components of our Earth-system model with neural emulators. Seeking a probabilistic-ML collaborator with surrogate-modeling experience.",
    longDescription: "Our flagship Earth-system model is too expensive to run perturbed ensembles at the resolution policy work demands. We want to train Gaussian-process or neural-network surrogates on a sparse training set and propagate uncertainty cleanly through the coupled system. Funding application is in preparation; we are looking for co-investigators to co-author it before the call closes.",
    requiredSkills: ["machine learning", "Bayesian methods", "simulation"],
    niceSkills: ["climate modeling", "Fortran", "HPC"],
    candidateIds: ["r-patel", "r-nakamura"],
    matchPct: 64,
  },
  {
    id: "p-127",
    code: "DRS-2026-0127",
    title: "Ethics framework for synthetic-data clinical trials",
    discipline: "Ethics",
    status: "Open",
    posted: "3 weeks ago",
    deadline: "1 month",
    duration: "6 months",
    funded: true,
    lead: { name: "Dr. Sofía Marín", id: "r-marin", initials: "SM" },
    description: "Drafting a policy framework for trials that augment real patient cohorts with synthetic patients generated from longitudinal records. Looking for a statistician and a clinical-ethics co-author.",
    longDescription: "Synthetic patient cohorts are increasingly used to rescue underpowered subgroups in clinical trials. The regulatory framework has not caught up. This project drafts a position paper and accompanying decision framework for IRBs, jointly with the medical school's clinical-trials office.",
    requiredSkills: ["ethics review", "regulatory", "policy"],
    niceSkills: ["clinical trials", "statistics"],
    candidateIds: ["r-marin", "r-patel"],
    matchPct: 47,
  },
];

const ME = {
  initials: "TC",
  name: "Tara Chen",
  title: "PhD Candidate",
  discipline: "Bioengineering",
};

const INCOMING = [
  { id: "m-1", from: PROJECTS[0], status: "pending" },
  { id: "m-2", from: PROJECTS[2], status: "pending" },
];

const OUTGOING = [
  { id: "m-3", to: PROJECTS[1], status: "pending", sent: "2 days ago" },
  { id: "m-4", to: PROJECTS[3], status: "accepted", sent: "1 week ago" },
];

Object.assign(window, {
  DISCIPLINES, RESEARCHERS, PROJECTS, ME, INCOMING, OUTGOING,
});
